server:  port: 8091

spring:
  application:    name: servicio.prestamo
  datasource:    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prestamos
    username: postgres
    password: kurama86
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 200000
      connection-timeout: 30000
  jpa:
    properties:      hibernate:
        ddl-auto: udpate
        format-sql: true
        jdbc:
          lob:
            non-contextual-creation: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    
    
      
eureka:
  client:
    service-url: 
      default-zone: http://localhost:8761/eureka
    instances:
      status-page-url-path: /infoPrestamos
      health-check-url-path: /healthPrestamos

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health        hystrix:  command:    default:      circuitBreaker:        errorThresholdPercentage: 25    getCustomerOrderDetails:      execution:        isolation:          thread:            timeoutInMilliseconds: 3050    getCustomerProductRecommendation:      execution:        isolation:          thread:            timeoutInMilliseconds: 6500
        